CREATE SCHEMA `ASGARD`;

USE  `ASGARD`;

CREATE TABLE `ASGARD`.`TRAINERS` (

	`ID`  INT NOT NULL AUTO_INCREMENT,
    `FIRSTNAME`  VARCHAR(45) NOT NULL,
    `LASTNAME`   VARCHAR(45) NOT NULL,
    `SUBJECT` VARCHAR (45) NOT NULL,
    
    PRIMARY KEY (`ID`)
);

CREATE USER 'test'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES
ON ASGARD.*
TO 'test'@'localhost';